# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'WeScan' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeScan
  pod 'GoogleSignIn', '~> 4.4.0'
  pod 'GoogleAPIClientForREST/Drive', '~> 1.3.7'
  pod 'SwiftGifOrigin', '~> 1.7.0'

end
